import "./globals.css";
import Navbar from "../components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark h-screen">
        <Navbar/>
        <main className="h-[calc(100vh-4rem)]">
          {children}
        </main>
      </body>
    </html>
  );
}
